# yaml-language-server: $schema=https://json.schemastore.org/taskfile.json
---
version: "3"

env:
  PROFILE: home

tasks:
  default:
    desc: Show help
    aliases: [h]
    silent: true
    cmds:
      - task -l

  install:
    desc: Install files with dotbot
    aliases: [i]
    cmds:
      - ./install

  brew:save:
    desc: Save installed brews
    aliases: [bs]
    cmds:
      - cmd: rm -f brew/Brewfile.${PROFILE}
        silent: true
      - cmd: rm -f brew/Brewfile.${PROFILE}.leaves.txt
        silent: true
      - brew bundle dump --file=brew/Brewfile.${PROFILE}
      - brew leaves > brew/Brewfile.${PROFILE}.leaves.txt

  brew:install:
    desc: Install brew apps
    aliases: [bi]
    cmds:
      - brew bundle install --file=brew/Brewfile.${PROFILE}

  brew:deps-tree:
    desc: Save brew dependency tree
    aliases: [bt]
    cmds:
      - brew deps --tree --installed > brew-tree.txt
      - code brew-tree.txt

  install:all:
    desc: Install all (synlinks, brew)
    aliases: [ia]
    cmds:
      # run sequencialy
      - task: install
      - task: brew:install

  save:all:
    desc: Save current config
    aliases: [sa, save]
    cmds:
      - 'echo "Profile in use: ${PROFILE}"'
      # run in parallel
      - task: nodejs:save
