
[[Snippets]]
  Description = "SSH: Load ssh keys"
  Filename = "/Users/adamatti/.config/pet/snippet.toml"
  Output = ""
  Tag = ["ssh"]
  command = "eval `ssh-agent -s` && ssh-add ~/.ssh/id_rsa"

[[Snippets]]
  Description = "Git: undo latest commit"
  Filename = "/Users/adamatti/.config/pet/snippet.toml"
  Output = ""
  Tag = ["git"]
  command = "git reset --soft HEAD~"

[[Snippets]]
  Description = "Git: fetch all and prune"
  Filename = "/Users/adamatti/.config/pet/snippet.toml"
  Output = ""
  Tag = ["git"]
  command = "git fetch --all --prune --jobs=10"

[[Snippets]]
  Description = "Git: empty commit to trigger build"
  Filename = "/Users/adamatti/.config/pet/snippet.toml"
  Output = ""
  Tag = ["git"]
  command = "git commit --allow-empty -m \"chore: trigger build\""

[[Snippets]]
  Description = "Git: The old Gupa"
  Filename = "/Users/adamatti/.config/pet/snippet.toml"
  Output = ""
  Tag = ["git"]
  command = "git pull --rebase --autostash"

[[Snippets]]
  Description = "Docker: stop and remove all containers"
  Filename = "/Users/adamatti/.config/pet/snippet.toml"
  Output = ""
  Tag = ["docker"]
  command = "task -g docker:stop-and-remove"

[[Snippets]]
  Description = "Docker: stop all containers"
  Filename = "/Users/adamatti/.config/pet/snippet.toml"
  Output = ""
  Tag = ["docker"]
  command = "docker ps -aq | xargs docker stop"

[[Snippets]]
  Description = "Docker: remove all images"
  Filename = "/Users/adamatti/.config/pet/snippet.toml"
  Output = ""
  Tag = ["docker"]
  command = "docker image ls -q | xargs -I {} docker image rm -f {}"

[[Snippets]]
  Description = "Docker: image prune"
  Filename = "/Users/adamatti/.config/pet/snippet.toml"
  Output = ""
  Tag = ["docker"]
  command = "docker image prune --all --force"

[[Snippets]]
  Description = "Docker: full prune"
  Filename = "/Users/adamatti/.config/pet/snippet.toml"
  Output = ""
  Tag = ["docker"]
  command = "docker system prune"

[[Snippets]]
  Description = "DNS: refresh DNS"
  Filename = "/Users/adamatti/.config/pet/snippet.toml"
  Output = ""
  Tag = ["infra", "dns"]
  command = "sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder"

[[Snippets]]
  Description = "Cron: logs"
  Filename = "/Users/adamatti/.config/pet/snippet.toml"
  Output = ""
  Tag = ["cron"]
  command = "grep -i cron /var/log/system.log"

[[Snippets]]
  Description = "Brew: list pinned items"
  Filename = "/Users/adamatti/.config/pet/snippet.toml"
  Output = ""
  Tag = ["brew"]
  command = "brew list --pinned"

[[Snippets]]
  Description = "Brew: list casks"
  Filename = "/Users/adamatti/.config/pet/snippet.toml"
  Output = ""
  Tag = ["brew"]
  command = "brew cu"

[[Snippets]]
  Description = "Docker: list stopped containers"
  Filename = "/Users/adamatti/.config/pet/snippet.toml"
  Output = ""
  Tag = ["docker"]
  command = "docker ps --filter \"status=exited\""
