# yaml-language-server: $schema=https://json.schemastore.org/taskfile.json
---
version: "3"

includes:
  docker:
    aliases: [d]
    taskfile: ./Taskfile-docker.yaml

tasks:
  default:
    desc: Show help
    aliases: [h]
    silent: true
    cmds:
      - task -l --sort alphanumeric

  cleanup:
    desc: Cleanup routine
    cmds:
      - task: brew:cleanup
#     Temporary disabled
#     - task: mise:prune


  dotfiles:update:
    desc: Update dot files
    aliases: [ud, du]
    run: once
    interactive: true
    cmds:
      - cd ${DOTFILES_ROOT};git pull --rebase --autostash

  brew:cleanup:
    cmds:
      - brew cleanup --prune=all

  brew:update:
    desc: Update brew apps
    aliases: [ub, bu]
    run: once
    interactive: true
    # env:
      # https://github.com/Homebrew/brew/issues/14516#issuecomment-1418593313
      # HOMEBREW_NO_INSTALL_FROM_API: 1
    cmds:
      # - task: update-brew-git
      - brew update
      # - cmd: arch -arm64 brew upgrade --greedy
      # greedy = includes auto-updaters + latest
      - cmd: brew upgrade --greedy
        ignore_error: true
      - brew cu -a

  update-brew-git:
    cmds:
      - cd /opt/homebrew && git pull --rebase

  mise:update:
    desc: Update mise
    aliases: [um, mu]
    run: once
    interactive: true
    cmds:
      - mise upgrade --bump

  mise:prune:
    desc: Remove not needed apps
    aliases: [mp]
    cmds:
      - mise prune

  update:
    desc: Update libs and tools
    aliases: [u]
    run: once
    interactive: true
    cmds:
      - task: dotfiles:update
      - task: brew:update
      - task: mise:update
      - fish --command "fisher update"
      - task: cleanup

  weather:
    desc: Show weather for canoas
    aliases: [w]
    silent: true
    cmds:
      - curl wttr.in/canoas

  plan:
    desc: Show update plan
    aliases: [p]
    cmds:
      - brew outdated
      - mise outdated

  claude:
    desc: Open claude
    interactive: true
    ignore_error: true
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      # Kill claude-mem first
      - kill $(lsof -ti :37777)
      - pkill -f claude
      - brew upgrade claude-code
      - claude