# yaml-language-server: $schema=https://json.schemastore.org/taskfile.json
---
version: "3"

includes:
  docker:
    aliases: [d]
    taskfile: ./Taskfile-docker.yaml

tasks:
  default:
    desc: Show help
    aliases: [h]
    silent: true
    cmds:
      - task -l --sort alphanumeric

  update-dotfiles:
    desc: Update dot files
    aliases: [ud]
    run: once
    interactive: true
    cmds:
      - cd ${DOTFILES_ROOT};git pull --rebase --autostash

  update-brew:
    desc: Update brew apps
    aliases: [ub]
    run: once
    interactive: true
    env:
      # https://github.com/Homebrew/brew/issues/14516#issuecomment-1418593313
      HOMEBREW_NO_INSTALL_FROM_API: 1
    cmds:
      # - task: update-brew-git
      - brew update
      - cmd: arch -arm64 brew upgrade --greedy
        ignore_error: true
      - brew cleanup

  update-brew-git:
    cmds:
      - cd /opt/homebrew && git pull --rebase

  update-mise:
    desc: Update mise
    aliases: [um]
    run: once
    interactive: true
    cmds:
      - mise upgrade --bump

  update:
    desc: Update libs and tools
    aliases: [u]
    run: once
    interactive: true
    cmds:
      - task: update-dotfiles
      - task: update-brew
      - task: update-mise
      - fish --command "fisher update"
      - brew uninstall --cask docker --force
  #   - cmd: echo "To Update Oh-My-ZSH, pls run 'omz update'"
  #     silent: true

  weather:
    desc: Show weather for canoas
    aliases: [w]
    silent: true
    cmds:
      - curl wttr.in/canoas

  plan:
    desc: Show update plan
    aliases: [p]
    cmds:
      - brew outdated
      - mise outdated
