# yaml-language-server: $schema=https://json.schemastore.org/taskfile.json
---
version: "3"

includes:
  docker:
    aliases: [d]
    taskfile: ./Taskfile-docker.yaml

tasks:
  default:
    desc: Show help
    aliases: [h]
    silent: true
    cmds:
      - task -l

  update-dotfiles:
    desc: Update dot files
    aliases: [ud]
    run: once
    interactive: true
    cmds:
      - cd ${DOTFILES_ROOT};git pull --rebase --autostash

  update-brew:
    desc: Update brew apps
    aliases: [ub]
    run: once
    interactive: true
    cmds:
      - brew update
      - cmd: arch -arm64 brew upgrade --greedy
        ignore_error: true
      - brew cleanup

  update-mise:
    desc: Update mise
    aliases: [um]
    run: once
    interactive: true
    cmds:
      - mise upgrade

  update:
    desc: Update libs and tools
    aliases: [u]
    run: once
    interactive: true
    cmds:
      - task: update-dotfiles
      - task: update-brew
      - task: update-mise
      - cmd: echo "To Update Oh-My-ZSH, pls run 'omz update'"
        silent: true
  
  weather:
    desc: Show weather for canoas
    aliases: [w]
    silent: true
    cmds:
      - curl wttr.in/canoas
